export const LOGIN_USERS_REQUEST = "LOGIN_USERS_REQUEST"
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS"
export const LOGIN_USERS_FAILURE = "LOGIN_USERS_FAILURE"

export const UPDATE_USER_DETAILS_REQUEST = "UPDATE_USER_DETAILS_REQUEST"
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS"
export const UPDATE_USER_DETAILS_FAILURE = "UPDATE_USER_DETAILS_FAILURE"